name: validate-skill
on:
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Schema lint (placeholder)
        run: echo "ok" # TODO make validation
